**Diplomatura en Ciencia de Datos, Aprendizaje Automático y sus Aplicaciones**

**Exploración y Curación de Datos**

*Edición 2022*

----

# Trabajo práctico entregable - parte 1

En esta notebook, vamos a cargar el conjunto de datos de [la compentencia Kaggle](https://www.kaggle.com/dansbecker/melbourne-housing-snapshot) sobre estimación de precios de ventas de propiedades en Melbourne, Australia.

Utilizaremos el conjunto de datos reducido producido por [DanB](https://www.kaggle.com/dansbecker). Hemos subido una copia a un servidor de la Universidad Nacional de Córdoba para facilitar su acceso remoto.

In [2]:
import matplotlib.pyplot as plt
import numpy
import pandas

import seaborn
seaborn.set_context('talk')

# from decouple import config
from sqlalchemy import create_engine, text

In [4]:
import plotly
plotly.__version__
# Make sure it's 4.14.3

'5.8.0'

In [5]:
melb_df = pandas.read_csv(
    'https://cs.famaf.unc.edu.ar/~mteruel/datasets/diplodatos/melb_data.csv')
melb_df[:3]

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0

## Ejercicio 1 SQL: 

1. Crear una base de datos en SQLite utilizando la libreria [SQLalchemy](https://stackoverflow.com/questions/2268050/execute-sql-from-file-in-sqlalchemy).
https://docs.sqlalchemy.org/en/14/core/engines.html#sqlite

In [6]:
engine = create_engine('sqlite:///foo.db')

2. Ingestar los datos provistos en 'https://cs.famaf.unc.edu.ar/~mteruel/datasets/diplodatos/melb_data.csv' en una tabla y el dataset generado en clase con datos de airbnb y sus precios por codigo postal en otra.

In [7]:
airbnb_df = pandas.read_csv('https://cs.famaf.unc.edu.ar/~mteruel/datasets/diplodatos/cleansed_listings_dec18.csv')

/var/folders/g3/60y3stx94570x_f9zydtwpsm0000gn/T/ipykernel_78259/3779282522.py:1: DtypeWarning: Columns (35,77) have mixed types. Specify dtype option on import or set low_memory=False.
  airbnb_df = pandas.read_csv('https://cs.famaf.unc.edu.ar/~mteruel/datasets/diplodatos/cleansed_listings_dec18.csv')

In [8]:
airbnb_df[:3]

,id,listing_url,scrape_id,last_scraped,name,summary,space,description,neighborhood_overview,notes,...,review_scores_location,review_scores_value,requires_license,license,instant_bookable,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,reviews_per_month
0,9835,https://www.airbnb.com/rooms/9835,2.018120e+13,12/7/2018,Beautiful Room & House,NaN,"House: Clean, New, Modern, Quite, Safe. 10Km f...","House: Clean, New, Modern, Quite, Safe. 10Km f...",Very safe! Family oriented. Older age group.,NaN,...,9.0,9.0,f,NaN,f,strict_14_with_grace_period,f,f,1,0.04
1,10803,https://www.airbnb.com/rooms/10803,2.018120e+13,12/7/2018,Room in Cool Deco Apartment in Brunswick,A large air conditioned room with queen spring...,The apartment is Deco/Edwardian in style and h...,A large air conditioned room with queen spring...,This hip area is a crossroads between two grea...,NaN,...,9.0,9.0,f,NaN,t,moderate,t,t,1,1.50
2,12936,https://www.airbnb.com/rooms/12936,2.018120e+13,12/7/2018,St Kilda 1BR APT+BEACHSIDE+VIEWS+PARKING+WIFI+AC,RIGHT IN THE HEART OF ST KILDA! It doesn't get...,FREE WiFi FREE in-building remote controlled g...,RIGHT IN THE HEART OF ST KILDA! It doesn't get...,A stay at our apartment means you can enjoy so...,First floor apartment with both lift and stair...,...,9.0,9.0,f,NaN,f,strict_14_with_grace_period,f,f,17,0.15

In [9]:
melb_df.to_sql('melb_data', con=engine, if_exists="replace")

13580

In [10]:
airbnb_df.to_sql('airbnb', con=engine, if_exists="replace")

22895

In [14]:
print(melb_df.columns)
print(airbnb_df.columns)

Index(['Suburb', 'Address', 'Rooms', 'Type', 'Price', 'Method', 'SellerG',
       'Date', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom', 'Car',
       'Landsize', 'BuildingArea', 'YearBuilt', 'CouncilArea', 'Lattitude',
       'Longtitude', 'Regionname', 'Propertycount'],
      dtype='object')
Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'name', 'summary',
       'space', 'description', 'neighborhood_overview', 'notes', 'transit',
       'access', 'interaction', 'house_rules', 'picture_url', 'host_id',
       'host_url', 'host_name', 'host_since', 'host_location', 'host_about',
       'host_response_time', 'host_response_rate', 'host_is_superhost',
       'host_thumbnail_url', 'host_picture_url', 'host_neighborhood',
       'host_verifications', 'host_has_profile_pic', 'host_identity_verified',
       'street', 'neighborhood', 'city', 'suburb', 'state', 'zipcode',
       'smart_location', 'country_code', 'country', 'latitude', 'longitude',
       'is_location_exact', 'property_type', 'room_type', 'accommodates',
       'bathrooms', 'bedrooms', 'beds', 'bed_type', 'amenities', 'price',
       'weekly_price', 'monthly_price', 'security_deposit', 'cleaning_fee',
       'guests_included', 'extra_people', 'minimum_nights', 'maximum_nights',
       'calendar_updated', 'has_availability', 'availability_30',
       'availability_60', 'availability_90', 'availability_365',
       'calendar_last_scraped', 'number_of_reviews', 'first_review',
       'last_review', 'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'requires_license', 'license',
       'instant_bookable', 'cancellation_policy',
       'require_guest_profile_picture', 'require_guest_phone_verification',
       'calculated_host_listings_count', 'reviews_per_month'],
      dtype='object')

3. Implementar consultas en SQL que respondan con la siguiente información:

    - cantidad de registros totales por ciudad.
    - cantidad de registros totales por barrio y ciudad.

In [28]:
query = """SELECT city, COUNT(city) 
FROM  airbnb
GROUP BY city"""

with engine.connect() as con:
      rs = con.execute(query)
      print(query)
      for row in rs:
          print(row)

SELECT city, COUNT(city)
FROM  airbnb
GROUP BY city
('Banyule', 203)
('Bayside', 375)
('Boroondara', 664)
('Brimbank', 108)
('Cardinia', 123)
('Casey', 153)
('Darebin', 698)
('Frankston', 177)
('Glen Eira', 631)
('Greater Dandenong', 147)
('Hobsons Bay', 239)
('Hume', 170)
('Kingston', 309)
('Knox', 175)
('Manningham', 313)
('Maribyrnong', 436)
('Maroondah', 115)
('Melbourne', 7368)
('Melton', 95)
('Monash', 571)
('Moonee Valley', 344)
('Moreland', 967)
('Nillumbik', 88)
('Port Phillip', 2808)
('Stonnington', 1621)
('Whitehorse', 614)
('Whittlesea', 137)
('Wyndham', 426)
('Yarra', 2049)
('Yarra Ranges', 771)

In [26]:
query = """SELECT city, neighborhood, COUNT(neighborhood) 
FROM  airbnb
GROUP BY city, neighborhood"""

with engine.connect() as con:
      rs = con.execute(query)
      print(query)
      for row in rs:
          print(row)

SELECT city, neighborhood, COUNT(neighborhood)
FROM  airbnb
GROUP BY city, neighborhood
('Banyule', None, 0)
('Banyule', 'Alphington', 16)
('Banyule', 'Preston', 8)
('Banyule', 'Thornbury', 5)
('Bayside', None, 0)
('Bayside', 'Bentleigh', 1)
('Bayside', 'Brighton', 203)
('Bayside', 'Elwood', 1)
('Boroondara', None, 0)
('Boroondara', 'Ashburton', 14)
('Boroondara', 'Balwyn', 70)
('Boroondara', 'Balwyn North', 40)
('Boroondara', 'Camberwell', 82)
('Boroondara', 'Canterbury', 24)
('Boroondara', 'Glen Iris', 32)
('Boroondara', 'Hawthorn', 261)
('Boroondara', 'Kew', 109)
('Boroondara', 'Malvern', 2)
('Brimbank', None, 0)
('Cardinia', None, 0)
('Casey', None, 0)
('Darebin', None, 0)
('Darebin', 'Alphington', 22)
('Darebin', 'Coburg', 4)
('Darebin', 'Northcote', 303)
('Darebin', 'Preston', 156)
('Darebin', 'Thornbury', 101)
('Frankston', None, 0)
('Glen Eira', None, 0)
('Glen Eira', 'Balaclava/Ripponlea', 2)
('Glen Eira', 'Bentleigh', 84)
('Glen Eira', 'Brighton', 2)
('Glen Eira', 'Carnegie', 126)
('Glen Eira', 'Caulfield', 299)
('Glen Eira', 'Ormond/McKinnon', 46)
('Glen Eira', 'St Kilda East', 39)
('Greater Dandenong', None, 0)
('Hobsons Bay', None, 0)
('Hobsons Bay', 'Newport', 45)
('Hobsons Bay', 'Spotswood/South Kingsville', 23)
('Hobsons Bay', 'Williamstown', 75)
('Hobsons Bay', 'Yarraville/Seddon', 6)
('Hume', None, 0)
('Kingston', None, 0)
('Kingston', 'Bentleigh', 17)
('Knox', None, 0)
('Manningham', None, 0)
('Manningham', 'Balwyn North', 17)
('Maribyrnong', None, 0)
('Maribyrnong', 'Footscray', 253)
('Maribyrnong', 'Yarraville/Seddon', 126)
('Maroondah', None, 0)
('Melbourne', None, 0)
('Melbourne', 'Brunswick', 7)
('Melbourne', 'Carlton', 582)
('Melbourne', 'Carlton North', 10)
('Melbourne', 'Central Business District', 3726)
('Melbourne', 'Docklands', 576)
('Melbourne', 'East Melbourne', 180)
('Melbourne', 'Flemington', 12)
('Melbourne', 'Kensington', 107)
('Melbourne', 'North Melbourne', 290)
('Melbourne', 'Parkville', 85)
('Melbourne', 'Port Melbourne', 8)
('Melbourne', 'Prahran/Windsor', 35)
('Melbourne', 'South Melbourne', 1)
('Melbourne', 'South Wharf', 24)
('Melbourne', 'South Yarra', 161)
('Melbourne', 'Southbank', 1204)
('Melbourne', 'West Melbourne', 119)
('Melton', None, 0)
('Monash', None, 0)
('Monash', 'Ashburton', 4)
('Monash', 'Bentleigh', 5)
('Monash', 'Carnegie', 24)
('Monash', 'Glen Iris', 5)
('Monash', 'Malvern East', 17)
('Moonee Valley', None, 0)
('Moonee Valley', 'Brunswick', 33)
('Moonee Valley', 'Flemington', 166)
('Moonee Valley', 'Kensington', 1)
('Moreland', None, 0)
('Moreland', 'Brunswick', 681)
('Moreland', 'Coburg', 144)
('Moreland', 'Fitzroy North', 6)
('Nillumbik', None, 0)
('Port Phillip', None, 0)
('Port Phillip', 'Albert Park', 74)
('Port Phillip', 'Balaclava/Ripponlea', 141)
('Port Phillip', 'Elwood', 308)
('Port Phillip', 'Middle Park', 50)
('Port Phillip', 'Port Melbourne', 243)
('Port Phillip', 'Prahran/Windsor', 156)
('Port Phillip', 'South Melbourne', 291)
('Port Phillip', 'South Yarra', 133)
('Port Phillip', 'Southbank', 44)
('Port Phillip', 'St Kilda', 1082)
('Port Phillip', 'St Kilda East', 159)
('Port Phillip', 'Windsor', 2)
('Stonnington', None, 0)
('Stonnington', 'Armadale', 71)
('Stonnington', 'Caulfield', 3)
('Stonnington', 'Glen Iris', 44)
('Stonnington', 'Malvern', 34)
('Stonnington', 'Malvern East', 100)
('Stonnington', 'Prahran', 257)
('Stonnington', 'Prahran/Windsor', 4)
('Stonnington', 'South Yarra', 759)
('Stonnington', 'St Kilda', 3)
('Stonnington', 'St Kilda East', 2)
('Stonnington', 'Toorak', 117)
('Stonnington', 'Windsor', 165)
('Whitehorse', None, 0)
('Whitehorse', 'Balwyn', 25)
('Whitehorse', 'Balwyn North', 4)
('Whitehorse', 'Camberwell', 10)
('Whitehorse', 'Glen Iris', 1)
('Whittlesea', None, 0)
('Wyndham', None, 0)
('Yarra', None, 0)
('Yarra', 'Abbotsford', 254)
('Yarra', 'Alphington', 16)
('Yarra', 'Brunswick', 7)
('Yarra', 'Burnley', 56)
('Yarra', 'Carlton', 3)
('Yarra', 'Carlton North', 128)
('Yarra', 'Clifton Hill', 59)
('Yarra', 'Collingwood', 283)
('Yarra', 'East Melbourne', 8)
('Yarra', 'Fitzroy', 381)
('Yarra', 'Fitzroy North', 225)
('Yarra', 'Northcote', 6)
('Yarra', 'Richmond', 547)
('Yarra Ranges', None, 0)

4. Combinar los datasets de ambas tablas ingestadas utilizando el comando JOIN de SQL  para obtener un resultado similar a lo realizado con Pandas en clase.

In [25]:
query = """
SELECT m.postcode, a.zipcode, a.price, m.price
FROM melb_data m
INNER JOIN airbnb a ON m.Postcode=a.zipcode
LIMIT 1000
"""

with engine.connect() as con:
      rs = con.execute(query)
      print(query)
      for row in rs:
          print(row)

SELECT m.postcode, a.zipcode, a.price, m.price
FROM melb_data m
INNER JOIN airbnb a ON m.Postcode=a.zipcode
LIMIT 1000

(3105.0, '3105', 60, 599900.0)
(3105.0, '3105', 60, 760000.0)
(3105.0, '3105', 60, 787000.0)
(3105.0, '3105', 60, 794000.0)
(3105.0, '3105', 60, 812500.0)
(3105.0, '3105', 60, 833000.0)
(3105.0, '3105', 60, 851000.0)
(3105.0, '3105', 60, 860000.0)
(3105.0, '3105', 60, 880000.0)
(3105.0, '3105', 60, 890000.0)
(3105.0, '3105', 60, 903000.0)
(3105.0, '3105', 60, 905000.0)
(3105.0, '3105', 60, 910000.0)
(3105.0, '3105', 60, 950000.0)
(3105.0, '3105', 60, 975000.0)
(3105.0, '3105', 60, 976000.0)
(3105.0, '3105', 60, 980000.0)
(3105.0, '3105', 60, 980000.0)
(3105.0, '3105', 60, 980000.0)
(3105.0, '3105', 60, 990000.0)
(3105.0, '3105', 60, 990000.0)
(3105.0, '3105', 60, 1000000.0)
(3105.0, '3105', 60, 1002000.0)
(3105.0, '3105', 60, 1050000.0)
(3105.0, '3105', 60, 1060000.0)
(3105.0, '3105', 60, 1060000.0)
(3105.0, '3105', 60, 1063000.0)
(3105.0, '3105', 60, 1075000.0)
(3105.0, '3105', 60, 1085000.0)
(3105.0, '3105', 60, 1100000.0)
(3105.0, '3105', 60, 1100000.0)
(3105.0, '3105', 60, 1100000.0)
(3105.0, '3105', 60, 1110000.0)
(3105.0, '3105', 60, 1127000.0)
(3105.0, '3105', 60, 1140000.0)
(3105.0, '3105', 60, 1160000.0)
(3105.0, '3105', 60, 1200000.0)
(3105.0, '3105', 60, 1207000.0)
(3105.0, '3105', 60, 1225000.0)
(3105.0, '3105', 60, 1225000.0)
(3105.0, '3105', 60, 1230000.0)
(3105.0, '3105', 60, 1235000.0)
(3105.0, '3105', 60, 1240000.0)
(3105.0, '3105', 60, 1244000.0)
(3105.0, '3105', 60, 1250000.0)
(3105.0, '3105', 60, 1250000.0)
(3105.0, '3105', 60, 1260000.0)
(3105.0, '3105', 60, 1280000.0)
(3105.0, '3105', 60, 1300000.0)
(3105.0, '3105', 60, 1300000.0)
(3105.0, '3105', 60, 1300000.0)
(3105.0, '3105', 60, 1300000.0)
(3105.0, '3105', 60, 1302000.0)
(3105.0, '3105', 60, 1303000.0)
(3105.0, '3105', 60, 1310000.0)
(3105.0, '3105', 60, 1320000.0)
(3105.0, '3105', 60, 1320000.0)
(3105.0, '3105', 60, 1331000.0)
(3105.0, '3105', 60, 1336000.0)
(3105.0, '3105', 60, 1340000.0)
(3105.0, '3105', 60, 1351000.0)
(3105.0, '3105', 60, 1360000.0)
(3105.0, '3105', 60, 1400000.0)
(3105.0, '3105', 60, 1401000.0)
(3105.0, '3105', 60, 1475000.0)
(3105.0, '3105', 60, 1490000.0)
(3105.0, '3105', 60, 1505000.0)
(3105.0, '3105', 60, 1540000.0)
(3105.0, '3105', 60, 1580000.0)
(3105.0, '3105', 60, 1730000.0)
(3105.0, '3105', 60, 1751000.0)
(3057.0, '3057', 35, 290000.0)
(3057.0, '3057', 35, 320000.0)
(3057.0, '3057', 35, 370000.0)
(3057.0, '3057', 35, 385000.0)
(3057.0, '3057', 35, 390000.0)
(3057.0, '3057', 35, 390500.0)
(3057.0, '3057', 35, 400000.0)
(3057.0, '3057', 35, 420000.0)
(3057.0, '3057', 35, 435000.0)
(3057.0, '3057', 35, 435000.0)
(3057.0, '3057', 35, 445000.0)
(3057.0, '3057', 35, 460000.0)
(3057.0, '3057', 35, 480000.0)
(3057.0, '3057', 35, 500000.0)
(3057.0, '3057', 35, 501000.0)
(3057.0, '3057', 35, 510000.0)
(3057.0, '3057', 35, 522000.0)
(3057.0, '3057', 35, 550000.0)
(3057.0, '3057', 35, 570000.0)
(3057.0, '3057', 35, 570000.0)
(3057.0, '3057', 35, 570000.0)
(3057.0, '3057', 35, 570000.0)
(3057.0, '3057', 35, 580000.0)
(3057.0, '3057', 35, 590000.0)
(3057.0, '3057', 35, 615000.0)
(3057.0, '3057', 35, 620000.0)
(3057.0, '3057', 35, 632000.0)
(3057.0, '3057', 35, 656000.0)
(3057.0, '3057', 35, 665000.0)
(3057.0, '3057', 35, 675000.0)
(3057.0, '3057', 35, 683000.0)
(3057.0, '3057', 35, 690000.0)
(3057.0, '3057', 35, 702500.0)
(3057.0, '3057', 35, 771000.0)
(3057.0, '3057', 35, 800000.0)
(3057.0, '3057', 35, 805000.0)
(3057.0, '3057', 35, 825000.0)
(3057.0, '3057', 35, 835000.0)
(3057.0, '3057', 35, 856000.0)
(3057.0, '3057', 35, 892000.0)
(3057.0, '3057', 35, 899000.0)
(3057.0, '3057', 35, 910000.0)
(3057.0, '3057', 35, 930000.0)
(3057.0, '3057', 35, 937000.0)
(3057.0, '3057', 35, 940000.0)
(3057.0, '3057', 35, 950000.0)
(3057.0, '3057', 35, 957000.0)
(3057.0, '3057', 35, 959000.0)
(3057.0, '3057', 35, 970000.0)
(3057.0, '3057', 35, 975000.0)
(3057.0, '3057', 35, 998000.0)
(3057.0, '3057', 35, 1010000.0)
(3057.0, '3057', 35, 1015000.0)
(3057.0, '3057', 35, 1023000.0)
(3057.0, '3057', 35, 1024000.0)
(3057.0, '3057', 35, 1025000.0)
(3057.0, '3057', 35, 1050000.0)
(3057.0, '3057', 35, 1050000.0)
(3057.0, '3057', 35, 1065000.0)
(3057.0, '3057', 35, 1080000.0)
(3057.0, '3057', 35, 1105000.0)
(3057.0, '3057', 35, 1125000.0)
(3057.0, '3057', 35, 1170000.0)
(3057.0, '3057', 35, 1185000.0)
(3057.0, '3057', 35, 1210000.0)
(3057.0, '3057', 35, 1220000.0)
(3057.0, '3057', 35, 1265000.0)
(3057.0, '3057', 35, 1265000.0)
(3057.0, '3057', 35, 1280000.0)
(3057.0, '3057', 35, 1283000.0)
(3057.0, '3057', 35, 1290000.0)
(3057.0, '3057', 35, 1305000.0)
(3057.0, '3057', 35, 1310000.0)
(3057.0, '3057', 35, 1310000.0)
(3057.0, '3057', 35, 1325000.0)
(3057.0, '3057', 35, 1330000.0)
(3057.0, '3057', 35, 1335000.0)
(3057.0, '3057', 35, 1350000.0)
(3057.0, '3057', 35, 1495000.0)
(3057.0, '3057', 35, 1500000.0)
(3057.0, '3057', 35, 1550000.0)
(3057.0, '3057', 35, 1574000.0)
(3057.0, '3057', 35, 1600000.0)
(3057.0, '3057', 35, 1615000.0)
(3057.0, '3057', 35, 1625000.0)
(3057.0, '3057', 35, 1679000.0)
(3057.0, '3057', 35, 1815000.0)
(3057.0, '3057', 35, 1900000.0)
(3182.0, '3182', 159, 320000.0)
(3182.0, '3182', 159, 320000.0)
(3182.0, '3182', 159, 330000.0)
(3182.0, '3182', 159, 335000.0)
(3182.0, '3182', 159, 346000.0)
(3182.0, '3182', 159, 350000.0)
(3182.0, '3182', 159, 350000.0)
(3182.0, '3182', 159, 354000.0)
(3182.0, '3182', 159, 360000.0)
(3182.0, '3182', 159, 360000.0)
(3182.0, '3182', 159, 360000.0)
(3182.0, '3182', 159, 365000.0)
(3182.0, '3182', 159, 366000.0)
(3182.0, '3182', 159, 370500.0)
(3182.0, '3182', 159, 380000.0)
(3182.0, '3182', 159, 380000.0)
(3182.0, '3182', 159, 385000.0)
(3182.0, '3182', 159, 385000.0)
(3182.0, '3182', 159, 390000.0)
(3182.0, '3182', 159, 392000.0)
(3182.0, '3182', 159, 395000.0)
(3182.0, '3182', 159, 400000.0)
(3182.0, '3182', 159, 400000.0)
(3182.0, '3182', 159, 400000.0)
(3182.0, '3182', 159, 400000.0)
(3182.0, '3182', 159, 400000.0)
(3182.0, '3182', 159, 420000.0)
(3182.0, '3182', 159, 420000.0)
(3182.0, '3182', 159, 430000.0)
(3182.0, '3182', 159, 430000.0)
(3182.0, '3182', 159, 430000.0)
(3182.0, '3182', 159, 431000.0)
(3182.0, '3182', 159, 435000.0)
(3182.0, '3182', 159, 450000.0)
(3182.0, '3182', 159, 450000.0)
(3182.0, '3182', 159, 450000.0)
(3182.0, '3182', 159, 451000.0)
(3182.0, '3182', 159, 451000.0)
(3182.0, '3182', 159, 452000.0)
(3182.0, '3182', 159, 455000.0)
(3182.0, '3182', 159, 459000.0)
(3182.0, '3182', 159, 460000.0)
(3182.0, '3182', 159, 461000.0)
(3182.0, '3182', 159, 465000.0)
(3182.0, '3182', 159, 468000.0)
(3182.0, '3182', 159, 470000.0)
(3182.0, '3182', 159, 470000.0)
(3182.0, '3182', 159, 470000.0)
(3182.0, '3182', 159, 475000.0)
(3182.0, '3182', 159, 475000.0)
(3182.0, '3182', 159, 475000.0)
(3182.0, '3182', 159, 480000.0)
(3182.0, '3182', 159, 481000.0)
(3182.0, '3182', 159, 481000.0)
(3182.0, '3182', 159, 482000.0)
(3182.0, '3182', 159, 482300.0)
(3182.0, '3182', 159, 487500.0)
(3182.0, '3182', 159, 495000.0)
(3182.0, '3182', 159, 500000.0)
(3182.0, '3182', 159, 500000.0)
(3182.0, '3182', 159, 500000.0)
(3182.0, '3182', 159, 500000.0)
(3182.0, '3182', 159, 503500.0)
(3182.0, '3182', 159, 509000.0)
(3182.0, '3182', 159, 517500.0)
(3182.0, '3182', 159, 520000.0)
(3182.0, '3182', 159, 520000.0)
(3182.0, '3182', 159, 520000.0)
(3182.0, '3182', 159, 525000.0)
(3182.0, '3182', 159, 530000.0)
(3182.0, '3182', 159, 530000.0)
(3182.0, '3182', 159, 533000.0)
(3182.0, '3182', 159, 535000.0)
(3182.0, '3182', 159, 535000.0)
(3182.0, '3182', 159, 540000.0)
(3182.0, '3182', 159, 542500.0)
(3182.0, '3182', 159, 550000.0)
(3182.0, '3182', 159, 560000.0)
(3182.0, '3182', 159, 561000.0)
(3182.0, '3182', 159, 565000.0)
(3182.0, '3182', 159, 570000.0)
(3182.0, '3182', 159, 570000.0)
(3182.0, '3182', 159, 571000.0)
(3182.0, '3182', 159, 575000.0)
(3182.0, '3182', 159, 575000.0)
(3182.0, '3182', 159, 580000.0)
(3182.0, '3182', 159, 580000.0)
(3182.0, '3182', 159, 582000.0)
(3182.0, '3182', 159, 586500.0)
(3182.0, '3182', 159, 600000.0)
(3182.0, '3182', 159, 602000.0)
(3182.0, '3182', 159, 610000.0)
(3182.0, '3182', 159, 610000.0)
(3182.0, '3182', 159, 610000.0)
(3182.0, '3182', 159, 610500.0)
(3182.0, '3182', 159, 615000.0)
(3182.0, '3182', 159, 616000.0)
(3182.0, '3182', 159, 640000.0)
(3182.0, '3182', 159, 640000.0)
(3182.0, '3182', 159, 648000.0)
(3182.0, '3182', 159, 650000.0)
(3182.0, '3182', 159, 680000.0)
(3182.0, '3182', 159, 685000.0)
(3182.0, '3182', 159, 690000.0)
(3182.0, '3182', 159, 700000.0)
(3182.0, '3182', 159, 701000.0)
(3182.0, '3182', 159, 720000.0)
(3182.0, '3182', 159, 730000.0)
(3182.0, '3182', 159, 750000.0)
(3182.0, '3182', 159, 757500.0)
(3182.0, '3182', 159, 760000.0)
(3182.0, '3182', 159, 785000.0)
(3182.0, '3182', 159, 808000.0)
(3182.0, '3182', 159, 875000.0)
(3182.0, '3182', 159, 875000.0)
(3182.0, '3182', 159, 902000.0)
(3182.0, '3182', 159, 902000.0)
(3182.0, '3182', 159, 920000.0)
(3182.0, '3182', 159, 920000.0)
(3182.0, '3182', 159, 1000000.0)
(3182.0, '3182', 159, 1000000.0)
(3182.0, '3182', 159, 1000000.0)
(3182.0, '3182', 159, 1030000.0)
(3182.0, '3182', 159, 1077000.0)
(3182.0, '3182', 159, 1100000.0)
(3182.0, '3182', 159, 1120000.0)
(3182.0, '3182', 159, 1120000.0)
(3182.0, '3182', 159, 1180000.0)
(3182.0, '3182', 159, 1190000.0)
(3182.0, '3182', 159, 1200500.0)
(3182.0, '3182', 159, 1210000.0)
(3182.0, '3182', 159, 1220000.0)
(3182.0, '3182', 159, 1225000.0)
(3182.0, '3182', 159, 1250000.0)
(3182.0, '3182', 159, 1295000.0)
(3182.0, '3182', 159, 1301000.0)
(3182.0, '3182', 159, 1316000.0)
(3182.0, '3182', 159, 1361000.0)
(3182.0, '3182', 159, 1365000.0)
(3182.0, '3182', 159, 1400000.0)
(3182.0, '3182', 159, 1435000.0)
(3182.0, '3182', 159, 1440000.0)
(3182.0, '3182', 159, 1500000.0)
(3182.0, '3182', 159, 1600000.0)
(3182.0, '3182', 159, 1600000.0)
(3182.0, '3182', 159, 1650000.0)
(3182.0, '3182', 159, 1678000.0)
(3182.0, '3182', 159, 1891000.0)
(3182.0, '3182', 159, 1900000.0)
(3182.0, '3182', 159, 1900000.0)
(3182.0, '3182', 159, 1950000.0)
(3182.0, '3182', 159, 2000000.0)
(3182.0, '3182', 159, 2000000.0)
(3182.0, '3182', 159, 2000000.0)
(3182.0, '3182', 159, 2220000.0)
(3182.0, '3182', 159, 2260000.0)
(3182.0, '3182', 159, 2455000.0)
(3182.0, '3182', 159, 2680000.0)
(3182.0, '3182', 159, 2720000.0)
(3182.0, '3182', 159, 4400000.0)
(3182.0, '3182', 159, 4750000.0)
(3182.0, '3182', 159, 5046000.0)
(3071.0, '3071', 50, 245000.0)
(3071.0, '3071', 50, 260000.0)
(3071.0, '3071', 50, 270000.0)
(3071.0, '3071', 50, 277500.0)
(3071.0, '3071', 50, 295000.0)
(3071.0, '3071', 50, 300000.0)
(3071.0, '3071', 50, 303500.0)
(3071.0, '3071', 50, 315000.0)
(3071.0, '3071', 50, 328000.0)
(3071.0, '3071', 50, 330000.0)
(3071.0, '3071', 50, 332000.0)
(3071.0, '3071', 50, 350000.0)
(3071.0, '3071', 50, 365000.0)
(3071.0, '3071', 50, 370000.0)
(3071.0, '3071', 50, 371000.0)
(3071.0, '3071', 50, 383000.0)
(3071.0, '3071', 50, 415000.0)
(3071.0, '3071', 50, 432500.0)
(3071.0, '3071', 50, 435000.0)
(3071.0, '3071', 50, 438000.0)
(3071.0, '3071', 50, 450000.0)
(3071.0, '3071', 50, 450000.0)
(3071.0, '3071', 50, 462000.0)
(3071.0, '3071', 50, 466000.0)
(3071.0, '3071', 50, 470000.0)
(3071.0, '3071', 50, 486000.0)
(3071.0, '3071', 50, 493000.0)
(3071.0, '3071', 50, 505000.0)
(3071.0, '3071', 50, 505000.0)
(3071.0, '3071', 50, 510000.0)
(3071.0, '3071', 50, 510000.0)
(3071.0, '3071', 50, 517500.0)
(3071.0, '3071', 50, 525500.0)
(3071.0, '3071', 50, 560000.0)
(3071.0, '3071', 50, 571750.0)
(3071.0, '3071', 50, 600000.0)
(3071.0, '3071', 50, 601000.0)
(3071.0, '3071', 50, 605000.0)
(3071.0, '3071', 50, 700000.0)
(3071.0, '3071', 50, 701000.0)
(3071.0, '3071', 50, 716000.0)
(3071.0, '3071', 50, 740000.0)
(3071.0, '3071', 50, 745000.0)
(3071.0, '3071', 50, 756000.0)
(3071.0, '3071', 50, 760000.0)
(3071.0, '3071', 50, 795000.0)
(3071.0, '3071', 50, 805000.0)
(3071.0, '3071', 50, 865000.0)
(3071.0, '3071', 50, 865000.0)
(3071.0, '3071', 50, 874000.0)
(3071.0, '3071', 50, 880000.0)
(3071.0, '3071', 50, 887000.0)
(3071.0, '3071', 50, 891000.0)
(3071.0, '3071', 50, 898000.0)
(3071.0, '3071', 50, 900000.0)
(3071.0, '3071', 50, 900000.0)
(3071.0, '3071', 50, 905000.0)
(3071.0, '3071', 50, 910000.0)
(3071.0, '3071', 50, 910500.0)
(3071.0, '3071', 50, 915000.0)
(3071.0, '3071', 50, 920000.0)
(3071.0, '3071', 50, 925000.0)
(3071.0, '3071', 50, 928500.0)
(3071.0, '3071', 50, 940000.0)
(3071.0, '3071', 50, 944000.0)
(3071.0, '3071', 50, 960000.0)
(3071.0, '3071', 50, 970000.0)
(3071.0, '3071', 50, 972000.0)
(3071.0, '3071', 50, 995000.0)
(3071.0, '3071', 50, 998000.0)
(3071.0, '3071', 50, 1000000.0)
(3071.0, '3071', 50, 1000000.0)
(3071.0, '3071', 50, 1010000.0)
(3071.0, '3071', 50, 1020000.0)
(3071.0, '3071', 50, 1031000.0)
(3071.0, '3071', 50, 1070000.0)
(3071.0, '3071', 50, 1080000.0)
(3071.0, '3071', 50, 1085000.0)
(3071.0, '3071', 50, 1100000.0)
(3071.0, '3071', 50, 1100000.0)
(3071.0, '3071', 50, 1100000.0)
(3071.0, '3071', 50, 1110000.0)
(3071.0, '3071', 50, 1110000.0)
(3071.0, '3071', 50, 1110000.0)
(3071.0, '3071', 50, 1130000.0)
(3071.0, '3071', 50, 1135000.0)
(3071.0, '3071', 50, 1143000.0)
(3071.0, '3071', 50, 1160000.0)
(3071.0, '3071', 50, 1164000.0)
(3071.0, '3071', 50, 1190000.0)
(3071.0, '3071', 50, 1195000.0)
(3071.0, '3071', 50, 1200000.0)
(3071.0, '3071', 50, 1200000.0)
(3071.0, '3071', 50, 1200000.0)
(3071.0, '3071', 50, 1200000.0)
(3071.0, '3071', 50, 1200000.0)
(3071.0, '3071', 50, 1200000.0)
(3071.0, '3071', 50, 1205500.0)
(3071.0, '3071', 50, 1210000.0)
(3071.0, '3071', 50, 1211000.0)
(3071.0, '3071', 50, 1225000.0)
(3071.0, '3071', 50, 1235000.0)
(3071.0, '3071', 50, 1236000.0)
(3071.0, '3071', 50, 1240000.0)
(3071.0, '3071', 50, 1245000.0)
(3071.0, '3071', 50, 1250000.0)
(3071.0, '3071', 50, 1250000.0)
(3071.0, '3071', 50, 1260000.0)
(3071.0, '3071', 50, 1265000.0)
(3071.0, '3071', 50, 1271000.0)
(3071.0, '3071', 50, 1272000.0)
(3071.0, '3071', 50, 1275000.0)
(3071.0, '3071', 50, 1280000.0)
(3071.0, '3071', 50, 1280000.0)
(3071.0, '3071', 50, 1290000.0)
(3071.0, '3071', 50, 1300000.0)
(3071.0, '3071', 50, 1345000.0)
(3071.0, '3071', 50, 1346000.0)
(3071.0, '3071', 50, 1370000.0)
(3071.0, '3071', 50, 1375000.0)
(3071.0, '3071', 50, 1380000.0)
(3071.0, '3071', 50, 1400000.0)
(3071.0, '3071', 50, 1400000.0)
(3071.0, '3071', 50, 1420000.0)
(3071.0, '3071', 50, 1427000.0)
(3071.0, '3071', 50, 1428888.0)
(3071.0, '3071', 50, 1430000.0)
(3071.0, '3071', 50, 1430000.0)
(3071.0, '3071', 50, 1450000.0)
(3071.0, '3071', 50, 1460000.0)
(3071.0, '3071', 50, 1478000.0)
(3071.0, '3071', 50, 1570000.0)
(3071.0, '3071', 50, 1605000.0)
(3071.0, '3071', 50, 1620000.0)
(3071.0, '3071', 50, 1626000.0)
(3071.0, '3071', 50, 1635000.0)
(3071.0, '3071', 50, 1750000.0)
(3071.0, '3071', 50, 1913000.0)
(3071.0, '3071', 50, 2070000.0)
(3183.0, '3183', 69, 280000.0)
(3183.0, '3183', 69, 290000.0)
(3183.0, '3183', 69, 328500.0)
(3183.0, '3183', 69, 410000.0)
(3183.0, '3183', 69, 416000.0)
(3183.0, '3183', 69, 440000.0)
(3183.0, '3183', 69, 442000.0)
(3183.0, '3183', 69, 450000.0)
(3183.0, '3183', 69, 474000.0)
(3183.0, '3183', 69, 490000.0)
(3183.0, '3183', 69, 497500.0)
(3183.0, '3183', 69, 500000.0)
(3183.0, '3183', 69, 502500.0)
(3183.0, '3183', 69, 520000.0)
(3183.0, '3183', 69, 540000.0)
(3183.0, '3183', 69, 585000.0)
(3183.0, '3183', 69, 600000.0)
(3183.0, '3183', 69, 700000.0)
(3183.0, '3183', 69, 820000.0)
(3183.0, '3183', 69, 981000.0)
(3183.0, '3183', 69, 1015000.0)
(3183.0, '3183', 69, 1080000.0)
(3183.0, '3183', 69, 1193000.0)
(3183.0, '3183', 69, 1475000.0)
(3183.0, '3183', 69, 1680000.0)
(3183.0, '3183', 69, 1690000.0)
(3183.0, '3183', 69, 1819000.0)
(3806.0, '3806', 98, 608500.0)
(3806.0, '3806', 98, 620000.0)
(3806.0, '3806', 98, 627500.0)
(3806.0, '3806', 98, 667000.0)
(3806.0, '3806', 98, 683000.0)
(3806.0, '3806', 98, 690000.0)
(3806.0, '3806', 98, 740000.0)
(3806.0, '3806', 98, 755000.0)
(3806.0, '3806', 98, 775000.0)
(3806.0, '3806', 98, 835000.0)
(3806.0, '3806', 98, 920000.0)
(3806.0, '3806', 98, 950000.0)
(3806.0, '3806', 98, 975000.0)
(3073.0, '3073', 50, 216000.0)
(3073.0, '3073', 50, 220000.0)
(3073.0, '3073', 50, 240000.0)
(3073.0, '3073', 50, 260000.0)
(3073.0, '3073', 50, 270000.0)
(3073.0, '3073', 50, 270000.0)
(3073.0, '3073', 50, 300000.0)
(3073.0, '3073', 50, 300000.0)
(3073.0, '3073', 50, 301000.0)
(3073.0, '3073', 50, 320000.0)
(3073.0, '3073', 50, 323000.0)
(3073.0, '3073', 50, 325000.0)
(3073.0, '3073', 50, 330000.0)
(3073.0, '3073', 50, 335000.0)
(3073.0, '3073', 50, 335000.0)
(3073.0, '3073', 50, 336000.0)
(3073.0, '3073', 50, 340000.0)
(3073.0, '3073', 50, 341000.0)
(3073.0, '3073', 50, 350000.0)
(3073.0, '3073', 50, 350000.0)
(3073.0, '3073', 50, 350000.0)
(3073.0, '3073', 50, 351000.0)
(3073.0, '3073', 50, 352000.0)
(3073.0, '3073', 50, 352000.0)
(3073.0, '3073', 50, 357500.0)
(3073.0, '3073', 50, 360000.0)
(3073.0, '3073', 50, 360000.0)
(3073.0, '3073', 50, 365000.0)
(3073.0, '3073', 50, 365000.0)
(3073.0, '3073', 50, 375000.0)
(3073.0, '3073', 50, 376000.0)
(3073.0, '3073', 50, 380000.0)
(3073.0, '3073', 50, 380000.0)
(3073.0, '3073', 50, 380000.0)
(3073.0, '3073', 50, 380000.0)
(3073.0, '3073', 50, 390000.0)
(3073.0, '3073', 50, 390000.0)
(3073.0, '3073', 50, 395000.0)
(3073.0, '3073', 50, 395000.0)
(3073.0, '3073', 50, 400000.0)
(3073.0, '3073', 50, 401000.0)
(3073.0, '3073', 50, 405000.0)
(3073.0, '3073', 50, 405000.0)
(3073.0, '3073', 50, 406000.0)
(3073.0, '3073', 50, 407000.0)
(3073.0, '3073', 50, 410000.0)
(3073.0, '3073', 50, 410000.0)
(3073.0, '3073', 50, 415000.0)
(3073.0, '3073', 50, 416000.0)
(3073.0, '3073', 50, 420000.0)
(3073.0, '3073', 50, 420000.0)
(3073.0, '3073', 50, 424000.0)
(3073.0, '3073', 50, 425000.0)
(3073.0, '3073', 50, 427500.0)
(3073.0, '3073', 50, 430000.0)
(3073.0, '3073', 50, 431000.0)
(3073.0, '3073', 50, 432000.0)
(3073.0, '3073', 50, 433000.0)
(3073.0, '3073', 50, 436000.0)
(3073.0, '3073', 50, 440000.0)
(3073.0, '3073', 50, 440000.0)
(3073.0, '3073', 50, 440000.0)
(3073.0, '3073', 50, 440000.0)
(3073.0, '3073', 50, 450000.0)
(3073.0, '3073', 50, 450000.0)
(3073.0, '3073', 50, 450000.0)
(3073.0, '3073', 50, 452000.0)
(3073.0, '3073', 50, 465000.0)
(3073.0, '3073', 50, 465000.0)
(3073.0, '3073', 50, 468000.0)
(3073.0, '3073', 50, 468000.0)
(3073.0, '3073', 50, 470000.0)
(3073.0, '3073', 50, 470000.0)
(3073.0, '3073', 50, 470000.0)
(3073.0, '3073', 50, 475000.0)
(3073.0, '3073', 50, 475000.0)
(3073.0, '3073', 50, 475000.0)
(3073.0, '3073', 50, 477000.0)
(3073.0, '3073', 50, 480000.0)
(3073.0, '3073', 50, 490000.0)
(3073.0, '3073', 50, 490000.0)
(3073.0, '3073', 50, 490000.0)
(3073.0, '3073', 50, 491000.0)
(3073.0, '3073', 50, 495000.0)
(3073.0, '3073', 50, 495000.0)
(3073.0, '3073', 50, 498000.0)
(3073.0, '3073', 50, 500000.0)
(3073.0, '3073', 50, 500000.0)
(3073.0, '3073', 50, 500250.0)
(3073.0, '3073', 50, 502000.0)
(3073.0, '3073', 50, 502500.0)
(3073.0, '3073', 50, 505000.0)
(3073.0, '3073', 50, 510000.0)
(3073.0, '3073', 50, 510000.0)
(3073.0, '3073', 50, 510000.0)
(3073.0, '3073', 50, 510000.0)
(3073.0, '3073', 50, 520000.0)
(3073.0, '3073', 50, 521000.0)
(3073.0, '3073', 50, 525000.0)
(3073.0, '3073', 50, 526250.0)
(3073.0, '3073', 50, 530000.0)
(3073.0, '3073', 50, 530000.0)
(3073.0, '3073', 50, 535000.0)
(3073.0, '3073', 50, 539000.0)
(3073.0, '3073', 50, 540000.0)
(3073.0, '3073', 50, 540000.0)
(3073.0, '3073', 50, 546000.0)
(3073.0, '3073', 50, 550000.0)
(3073.0, '3073', 50, 550000.0)
(3073.0, '3073', 50, 555000.0)
(3073.0, '3073', 50, 560000.0)
(3073.0, '3073', 50, 568000.0)
(3073.0, '3073', 50, 572000.0)
(3073.0, '3073', 50, 575000.0)
(3073.0, '3073', 50, 585000.0)
(3073.0, '3073', 50, 592000.0)
(3073.0, '3073', 50, 592500.0)
(3073.0, '3073', 50, 595000.0)
(3073.0, '3073', 50, 600000.0)
(3073.0, '3073', 50, 600000.0)
(3073.0, '3073', 50, 601000.0)
(3073.0, '3073', 50, 605000.0)
(3073.0, '3073', 50, 605000.0)
(3073.0, '3073', 50, 610000.0)
(3073.0, '3073', 50, 610000.0)
(3073.0, '3073', 50, 610000.0)
(3073.0, '3073', 50, 611000.0)
(3073.0, '3073', 50, 612500.0)
(3073.0, '3073', 50, 613000.0)

## Ejercicio 2: 

1. Seleccionar un subconjunto de columnas que les parezcan relevantes al problema de predicción del valor de la propiedad. Justificar las columnas seleccionadas y las que no lo fueron.
 - Eliminar los valores extremos que no sean relevantes para la predicción de valores de las propiedades.

2. Agregar información adicional respectiva al entorno de una propiedad a partir del [conjunto de datos de AirBnB](https://www.kaggle.com/tylerx/melbourne-airbnb-open-data?select=cleansed_listings_dec18.csv) utilizado en el práctico. 
  1. Seleccionar qué variables agregar y qué combinaciones aplicar a cada una. Por ejemplo, pueden utilizar solo la columna `price`, o aplicar múltiples transformaciones como la mediana o el mínimo.
  1. Utilizar la variable zipcode para unir los conjuntos de datos. Sólo incluir los zipcodes que tengan una cantidad mínima de registros (a elección) como para que la información agregada sea relevante.
  2. Investigar al menos otras 2 variables que puedan servir para combinar los datos, y justificar si serían adecuadas o no. Pueden asumir que cuentan con la ayuda de anotadores expertos para encontrar equivalencias entre barrios o direcciones, o que cuentan con algoritmos para encontrar las n ubicaciones más cercanas a una propiedad a partir de sus coordenadas geográficas. **NO** es necesario que realicen la implementación.

Pueden leer otras columnas del conjunto de AirBnB además de las que están en `interesting_cols`, si les parecen relevantes.

## Ejercicio 3:

Crear y guardar un nuevo conjunto de datos con todas las transformaciones realizadas anteriormente.

## Ejercicios opcionales:

1. Armar un script en python (archivo .py) [ETL](https://towardsdatascience.com/what-to-log-from-python-etl-pipelines-9e0cfe29950e) que corra los pasos de extraccion, transformacion y carga, armando una funcion para cada etapa del proceso y luego un main que corra todos los pasos requeridos.

2. Armar un DAG en Apache Airflow que corra el ETL. (https://airflow.apache.org/docs/apache-airflow/stable/tutorial.html)